//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maloncos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id_Clients { get; set; }
        public string Nom_Client { get; set; }
        public string Prenom_Client { get; set; }
        public string Adresse { get; set; }
        public string Code_postal { get; set; }
        public string Genre { get; set; }
        public string Email_Client { get; set; }
        public string Password { get; set; }
    }
}
