//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maloncos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_Command
    {
        public int Id_Ligne_Command { get; set; }
        public int Id_Command { get; set; }
        public int Id_vetement { get; set; }
        public double Montant { get; set; }
        public int Nombre_Article { get; set; }
        public string Adresse_livraison { get; set; }
        public string Adresse_Facturation { get; set; }
        public Nullable<double> Frais_Livraison { get; set; }
    }
}
