//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maloncos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soins
    {
        public int Id { get; set; }
        public string Type_produit { get; set; }
        public string Libelle { get; set; }
        public string Image { get; set; }
        public decimal Prix_produit { get; set; }
    }
}
