//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maloncos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vetements
    {
        public int Id_vetement { get; set; }
        public string Type_vetement { get; set; }
        public string Categorie { get; set; }
        public string Genre_vetement { get; set; }
        public string Reference_vetement { get; set; }
        public string Libelle_vetement { get; set; }
        public string Prix_vetement { get; set; }
        public string Couleur { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public Nullable<int> Prix_unit { get; set; }
    }
}
