//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenRevue.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class senrevueEntities : DbContext
    {
        public senrevueEntities()
            : base("name=senrevueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<content> content { get; set; }
        public virtual DbSet<image> image { get; set; }
        public virtual DbSet<label> label { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<title> title { get; set; }
    }
}
