//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenRevue.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int com_id { get; set; }
        public int art_id { get; set; }
        public int lng_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string com_username { get; set; }
        public string com_usermail { get; set; }
        public string com_text { get; set; }
    
        public virtual article article { get; set; }
        public virtual language language { get; set; }
    }
}
