//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenRevue.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class label
    {
        public int lbl_id { get; set; }
        public string lbl_code { get; set; }
        public int lng_id { get; set; }
        public string lbl_libelle { get; set; }
    
        public virtual language language { get; set; }
    }
}
